### ISSUE TITLE
Баг спавна

### ISSUE THREAD

**Issue by LiWinDom** [LiWinDom/metrostroi_81-740_part1#1]
При спавне состава, в головном вагоне выключены все автоматы и батареи. Их невозможно включить

**Comment by AntonBorisovich** [comment]
Это последний релиз?

**Comment by LiWinDom** [comment]
Да

**Comment by AntonBorisovich** [comment]
Зайди потом в дс и покажи, либо тут скрины приложи

**Comment by AntonBorisovich** [comment]
пофикшено
